const CountriesConstant = [
  {
    custom_country_icon: "AF",
    custom_dial_code: "+93",
    value: "Afghanistan",
    custom_country_value: "1",
  },
  {
    custom_country_icon: "AL",
    custom_dial_code: "+355",
    value: "Albania",
    custom_country_value: "2",
  },
  {
    custom_country_icon: "DZ",
    custom_dial_code: "+213",
    value: "Algeria",
    custom_country_value: "3",
  },
  {
    custom_country_icon: "AS",
    custom_dial_code: "+1684",
    value: "American Samoa",
    custom_country_value: "4",
  },
  {
    custom_country_icon: "AD",
    custom_dial_code: "+376",
    value: "Andorra",
    custom_country_value: "5",
  },
  {
    custom_country_icon: "AO",
    custom_dial_code: "+244",
    value: "Angola",
    custom_country_value: "6",
  },
  {
    custom_country_icon: "AI",
    custom_dial_code: "+1264",
    value: "Anguilla",
    custom_country_value: "7",
  },
  {
    custom_country_icon: "AQ",
    custom_dial_code: "+672",
    value: "Antarctica",
    custom_country_value: "8",
  },
  {
    custom_country_icon: "AG",
    custom_dial_code: "+1268",
    value: "Antigua And Barbudans",
    custom_country_value: "9",
  },
  {
    custom_country_icon: "AR",
    custom_dial_code: "+54",
    value: "Argentina",
    custom_country_value: "10",
  },
  {
    custom_country_icon: "AM",
    custom_dial_code: "+374",
    value: "Armenia",
    custom_country_value: "11",
  },
  {
    custom_country_icon: "AW",
    custom_dial_code: "+297",
    value: "Aruba",
    custom_country_value: "12",
  },
  {
    custom_country_icon: "AU",
    custom_dial_code: "+61",
    value: "Australia",
    custom_country_value: "13",
  },
  {
    custom_country_icon: "AT",
    custom_dial_code: "+43",
    value: "Austria",
    custom_country_value: "14",
  },
  {
    custom_country_icon: "AZ",
    custom_dial_code: "+994",
    value: "Azerbaijan",
    custom_country_value: "15",
  },
  {
    custom_country_icon: "BS",
    custom_dial_code: "+1242",
    value: "Bahamas The",
    custom_country_value: "16",
  },
  {
    custom_country_icon: "BH",
    custom_dial_code: "+973",
    value: "Bahrain",
    custom_country_value: "17",
  },
  {
    custom_country_icon: "BD",
    custom_dial_code: "+880",
    value: "Bangladesh",
    custom_country_value: "18",
  },
  {
    custom_country_icon: "BB",
    custom_dial_code: "+1246",
    value: "Barbados",
    custom_country_value: "19",
  },
  {
    custom_country_icon: "BY",
    custom_dial_code: "+375",
    value: "Belarus",
    custom_country_value: "20",
  },
  {
    custom_country_icon: "BE",
    custom_dial_code: "+32",
    value: "Belgium",
    custom_country_value: "21",
  },
  {
    custom_country_icon: "BZ",
    custom_dial_code: "+501",
    value: "Belize",
    custom_country_value: "22",
  },
  {
    custom_country_icon: "BJ",
    custom_dial_code: "+229",
    value: "Benin",
    custom_country_value: "23",
  },
  {
    custom_country_icon: "BM",
    custom_dial_code: "+1441",
    value: "Bermuda",
    custom_country_value: "24",
  },
  {
    custom_country_icon: "BT",
    custom_dial_code: "+975",
    value: "Bhutan",
    custom_country_value: "25",
  },
  {
    custom_country_icon: "BO",
    custom_dial_code: "+591",
    value: "Bolivia",
    custom_country_value: "26",
  },
  {
    custom_country_icon: "BA",
    custom_dial_code: "+387",
    value: "Bosnia and Herzegovina",
    custom_country_value: "27",
  },
  {
    custom_country_icon: "BW",
    custom_dial_code: "+267",
    value: "Botswana",
    custom_country_value: "28",
  },
  {
    custom_country_icon: "BV",
    custom_dial_code: "+55",
    value: "Bouvet Island",
    custom_country_value: "29",
  },
  {
    custom_country_icon: "BR",
    custom_dial_code: "+55",
    value: "Brazil",
    custom_country_value: "30",
  },
  {
    custom_country_icon: "IO",
    custom_dial_code: "+246",
    value: "British Indian Ocean Territory",
    custom_country_value: "31",
  },
  {
    custom_country_icon: "BN",
    custom_dial_code: "+673",
    value: "Brunei",
    custom_country_value: "32",
  },
  {
    custom_country_icon: "BG",
    custom_dial_code: "+359",
    value: "Bulgaria",
    custom_country_value: "33",
  },
  {
    custom_country_icon: "BF",
    custom_dial_code: "+226",
    value: "Burkina Faso",
    custom_country_value: "34",
  },
  {
    custom_country_icon: "BI",
    custom_dial_code: "+257",
    value: "Burundi",
    custom_country_value: "35",
  },
  {
    custom_country_icon: "KH",
    custom_dial_code: "+855",
    value: "Cambodia",
    custom_country_value: "36",
  },
  {
    custom_country_icon: "CM",
    custom_dial_code: "+237",
    value: "Cameroon",
    custom_country_value: "37",
  },
  {
    custom_country_icon: "CA",
    custom_dial_code: "+1",
    value: "Canada",
    custom_country_value: "38",
  },
  {
    custom_country_icon: "CV",
    custom_dial_code: "+238",
    value: "Cape Verde",
    custom_country_value: "39",
  },
  {
    custom_country_icon: "KY",
    custom_dial_code: "+1345",
    value: "Cayman Islands",
    custom_country_value: "40",
  },
  {
    custom_country_icon: "CF",
    custom_dial_code: "+236",
    value: "Central African Republic",
    custom_country_value: "41",
  },
  {
    custom_country_icon: "TD",
    custom_dial_code: "+235",
    value: "Chad",
    custom_country_value: "42",
  },
  {
    custom_country_icon: "CL",
    custom_dial_code: "+56",
    value: "Chile",
    custom_country_value: "43",
  },
  {
    custom_country_icon: "CN",
    custom_dial_code: "+86",
    value: "China",
    custom_country_value: "44",
  },
  {
    custom_country_icon: "CX",
    custom_dial_code: "+61",
    value: "Christmas Island",
    custom_country_value: "45",
  },
  {
    custom_country_icon: "CC",
    custom_dial_code: "+891",
    value: "Cocos (Keeling) Islands",
    custom_country_value: "46",
  },
  {
    custom_country_icon: "CO",
    custom_dial_code: "+57",
    value: "Colombia",
    custom_country_value: "47",
  },
  {
    custom_country_icon: "KM",
    custom_dial_code: "+269",
    value: "Comoros",
    custom_country_value: "48",
  },
  {
    custom_country_icon: "CG",
    custom_dial_code: "+242",
    value: "Congo",
    custom_country_value: "49",
  },
  {
    custom_country_icon: "CD",
    custom_dial_code: "+243",
    value: "Congo The Democratic Republic Of The",
    custom_country_value: "50",
  },
  {
    custom_country_icon: "CK",
    custom_dial_code: "+682",
    value: "Cook Islands",
    custom_country_value: "51",
  },
  {
    custom_country_icon: "CR",
    custom_dial_code: "+506",
    value: "Costa Rica",
    custom_country_value: "52",
  },
  {
    custom_country_icon: "CI",
    custom_dial_code: "+225",
    value: "Cote D'Ivoire (Ivory Coast)",
    custom_country_value: "53",
  },
  {
    custom_country_icon: "HR",
    custom_dial_code: "+385",
    value: "Croatia (Hrvatska)",
    custom_country_value: "54",
  },
  {
    custom_country_icon: "CU",
    custom_dial_code: "+53",
    value: "Cuba",
    custom_country_value: "55",
  },
  {
    custom_country_icon: "CY",
    custom_dial_code: "+357",
    value: "Cyprus",
    custom_country_value: "56",
  },
  {
    custom_country_icon: "CZ",
    custom_dial_code: "+420",
    value: "Czechia",
    custom_country_value: "57",
  },
  {
    custom_country_icon: "DK",
    custom_dial_code: "+45",
    value: "Denmark",
    custom_country_value: "58",
  },
  {
    custom_country_icon: "DJ",
    custom_dial_code: "+253",
    value: "Djibouti",
    custom_country_value: "59",
  },
  {
    custom_country_icon: "DM",
    custom_dial_code: "+1767",
    value: "Dominica",
    custom_country_value: "60",
  },
  {
    custom_country_icon: "DO",
    custom_dial_code: "+1809",
    value: "Dominican Republic",
    custom_country_value: "61",
  },
  {
    custom_country_icon: "BH",
    custom_dial_code: "+670",
    value: "East Timor",
    custom_country_value: "62",
  },
  {
    custom_country_icon: "EC",
    custom_dial_code: "+593",
    value: "Ecuador",
    custom_country_value: "63",
  },
  {
    custom_country_icon: "EG",
    custom_dial_code: "+20",
    value: "Egypt",
    custom_country_value: "64",
  },
  {
    custom_country_icon: "SV",
    custom_dial_code: "+503",
    value: "El Salvador",
    custom_country_value: "65",
  },
  {
    custom_country_icon: "GQ",
    custom_dial_code: "+240",
    value: "Equatorial Guinea",
    custom_country_value: "66",
  },
  {
    custom_country_icon: "ER",
    custom_dial_code: "+291",
    value: "Eritrea",
    custom_country_value: "67",
  },
  {
    custom_country_icon: "EE",
    custom_dial_code: "+372",
    value: "Estonia",
    custom_country_value: "68",
  },
  {
    custom_country_icon: "ET",
    custom_dial_code: "+251",
    value: "Ethiopia",
    custom_country_value: "69",
  },
  {
    custom_country_icon: "BH",
    custom_dial_code: "+672",
    value: "External Territories of Australia",
    custom_country_value: "70",
  },
  {
    custom_country_icon: "FK",
    custom_dial_code: "+500",
    value: "Falkland Islands",
    custom_country_value: "71",
  },
  {
    custom_country_icon: "FO",
    custom_dial_code: "+298",
    value: "Faroe Islands",
    custom_country_value: "72",
  },
  {
    custom_country_icon: "FJ",
    custom_dial_code: "+679",
    value: "Fiji Islands",
    custom_country_value: "73",
  },
  {
    custom_country_icon: "FI",
    custom_dial_code: "+358",
    value: "Finland",
    custom_country_value: "74",
  },
  {
    custom_country_icon: "FR",
    custom_dial_code: "+33",
    value: "France",
    custom_country_value: "75",
  },
  {
    custom_country_icon: "GF",
    custom_dial_code: "+594",
    value: "French Guiana",
    custom_country_value: "76",
  },
  {
    custom_country_icon: "PF",
    custom_dial_code: "+689",
    value: "French Polynesia",
    custom_country_value: "77",
  },
  {
    custom_country_icon: "TF",
    custom_dial_code: "+262",
    value: "French Southern Territories",
    custom_country_value: "78",
  },
  {
    custom_country_icon: "GA",
    custom_dial_code: "+241",
    value: "Gabon",
    custom_country_value: "79",
  },
  {
    custom_country_icon: "GM",
    custom_dial_code: "+220",
    value: "Gambia The",
    custom_country_value: "80",
  },
  {
    custom_country_icon: "GE",
    custom_dial_code: "+995",
    value: "Georgia",
    custom_country_value: "81",
  },
  {
    custom_country_icon: "DE",
    custom_dial_code: "+49",
    value: "Germany",
    custom_country_value: "82",
  },
  {
    custom_country_icon: "GH",
    custom_dial_code: "+233",
    value: "Ghana",
    custom_country_value: "83",
  },
  {
    custom_country_icon: "GI",
    custom_dial_code: "+350",
    value: "Gibraltar",
    custom_country_value: "84",
  },
  {
    custom_country_icon: "GR",
    custom_dial_code: "+30",
    value: "Greece",
    custom_country_value: "85",
  },
  {
    custom_country_icon: "GL",
    custom_dial_code: "+299",
    value: "Greenland",
    custom_country_value: "86",
  },
  {
    custom_country_icon: "GD",
    custom_dial_code: "+1473",
    value: "Grenada",
    custom_country_value: "87",
  },
  {
    custom_country_icon: "GP",
    custom_dial_code: "+590",
    value: "Guadeloupe",
    custom_country_value: "88",
  },
  {
    custom_country_icon: "GU",
    custom_dial_code: "+1671",
    value: "Guam",
    custom_country_value: "89",
  },
  {
    custom_country_icon: "GT",
    custom_dial_code: "+502",
    value: "Guatemala",
    custom_country_value: "90",
  },
  {
    custom_country_icon: "BH",
    custom_dial_code: "+44",
    value: "Guernsey and Alderney",
    custom_country_value: "91",
  },
  {
    custom_country_icon: "GN",
    custom_dial_code: "+224",
    value: "Guinea",
    custom_country_value: "92",
  },
  {
    custom_country_icon: "GW",
    custom_dial_code: "+245",
    value: "Guinea-Bissau",
    custom_country_value: "93",
  },
  {
    custom_country_icon: "GY",
    custom_dial_code: "+592",
    value: "Guyana",
    custom_country_value: "94",
  },
  {
    custom_country_icon: "HT",
    custom_dial_code: "+509",
    value: "Haiti",
    custom_country_value: "95",
  },
  {
    custom_country_icon: "HM",
    custom_dial_code: "+1672",
    value: "Heard and McDonald Islands",
    custom_country_value: "96",
  },
  {
    custom_country_icon: "HN",
    custom_dial_code: "+504",
    value: "Honduras",
    custom_country_value: "97",
  },
  {
    custom_country_icon: "HK",
    custom_dial_code: "+852",
    value: "Hong Kong S.A.R.",
    custom_country_value: "98",
  },
  {
    custom_country_icon: "HU",
    custom_dial_code: "+36",
    value: "Hungary",
    custom_country_value: "99",
  },
  {
    custom_country_icon: "IS",
    custom_dial_code: "+354",
    value: "Iceland",
    custom_country_value: "100",
  },
  {
    custom_country_icon: "IN",
    custom_dial_code: "+91",
    value: "India",
    custom_country_value: "101",
  },
  {
    custom_country_icon: "ID",
    custom_dial_code: "+62",
    value: "Indonesia",
    custom_country_value: "102",
  },
  {
    custom_country_icon: "IR",
    custom_dial_code: "+98",
    value: "Iran",
    custom_country_value: "103",
  },
  {
    custom_country_icon: "IQ",
    custom_dial_code: "+964",
    value: "Iraq",
    custom_country_value: "104",
  },
  {
    custom_country_icon: "IE",
    custom_dial_code: "+353",
    value: "Ireland",
    custom_country_value: "105",
  },
  {
    custom_country_icon: "IL",
    custom_dial_code: "+972",
    value: "Israel",
    custom_country_value: "106",
  },
  {
    custom_country_icon: "IT",
    custom_dial_code: "+39",
    value: "Italy",
    custom_country_value: "107",
  },
  {
    custom_country_icon: "JM",
    custom_dial_code: "+1876",
    value: "Jamaica",
    custom_country_value: "108",
  },
  {
    custom_country_icon: "JP",
    custom_dial_code: "+81",
    value: "Japan",
    custom_country_value: "109",
  },
  {
    custom_country_icon: "JE",
    custom_dial_code: "+44",
    value: "Jersey",
    custom_country_value: "110",
  },
  {
    custom_country_icon: "JO",
    custom_dial_code: "+962",
    value: "Jordan",
    custom_country_value: "111",
  },
  {
    custom_country_icon: "KZ",
    custom_dial_code: "+7",
    value: "Kazakhstan",
    custom_country_value: "112",
  },
  {
    custom_country_icon: "KE",
    custom_dial_code: "+254",
    value: "Kenya",
    custom_country_value: "113",
  },
  {
    custom_country_icon: "KI",
    custom_dial_code: "+686",
    value: "Kiribati",
    custom_country_value: "114",
  },
  {
    custom_country_icon: "KP",
    custom_dial_code: "+850",
    value: "Korea North",
    custom_country_value: "115",
  },
  {
    custom_country_icon: "KR",
    custom_dial_code: "+82",
    value: "Korea South",
    custom_country_value: "116",
  },
  {
    custom_country_icon: "KW",
    custom_dial_code: "+965",
    value: "Kuwait",
    custom_country_value: "117",
  },
  {
    custom_country_icon: "KG",
    custom_dial_code: "+996",
    value: "Kyrgyzstan",
    custom_country_value: "118",
  },
  {
    custom_country_icon: "LA",
    custom_dial_code: "+856",
    value: "Laos",
    custom_country_value: "119",
  },
  {
    custom_country_icon: "LV",
    custom_dial_code: "+371",
    value: "Latvia",
    custom_country_value: "120",
  },
  {
    custom_country_icon: "LB",
    custom_dial_code: "+961",
    value: "Lebanon",
    custom_country_value: "121",
  },
  {
    custom_country_icon: "LS",
    custom_dial_code: "+266",
    value: "Lesotho",
    custom_country_value: "122",
  },
  {
    custom_country_icon: "LR",
    custom_dial_code: "+231",
    value: "Liberia",
    custom_country_value: "123",
  },
  {
    custom_country_icon: "LY",
    custom_dial_code: "+218",
    value: "Libya",
    custom_country_value: "124",
  },
  {
    custom_country_icon: "LI",
    custom_dial_code: "+423",
    value: "Liechtenstein",
    custom_country_value: "125",
  },
  {
    custom_country_icon: "LT",
    custom_dial_code: "+370",
    value: "Lithuania",
    custom_country_value: "126",
  },
  {
    custom_country_icon: "LU",
    custom_dial_code: "+352",
    value: "Luxembourg",
    custom_country_value: "127",
  },
  {
    custom_country_icon: "MO",
    custom_dial_code: "+853",
    value: "Macau S.A.R.",
    custom_country_value: "128",
  },
  {
    custom_country_icon: "MK",
    custom_dial_code: "+389",
    value: "Macedonia",
    custom_country_value: "129",
  },
  {
    custom_country_icon: "MG",
    custom_dial_code: "+261",
    value: "Madagascar",
    custom_country_value: "130",
  },
  {
    custom_country_icon: "MW",
    custom_dial_code: "+265",
    value: "Malawi",
    custom_country_value: "131",
  },
  {
    custom_country_icon: "MY",
    custom_dial_code: "+60",
    value: "Malaysia",
    custom_country_value: "132",
  },
  {
    custom_country_icon: "MV",
    custom_dial_code: "+960",
    value: "Maldives",
    custom_country_value: "133",
  },
  {
    custom_country_icon: "ML",
    custom_dial_code: "+223",
    value: "Mali",
    custom_country_value: "134",
  },
  {
    custom_country_icon: "MT",
    custom_dial_code: "+356",
    value: "Malta",
    custom_country_value: "135",
  },
  {
    custom_country_icon: "BH",
    custom_dial_code: "+44",
    value: "Man (Isle of)",
    custom_country_value: "136",
  },
  {
    custom_country_icon: "MH",
    custom_dial_code: "+692",
    value: "Marshall Islands",
    custom_country_value: "137",
  },
  {
    custom_country_icon: "MQ",
    custom_dial_code: "+596",
    value: "Martinique",
    custom_country_value: "138",
  },
  {
    custom_country_icon: "MR",
    custom_dial_code: "+222",
    value: "Mauritania",
    custom_country_value: "139",
  },
  {
    custom_country_icon: "MU",
    custom_dial_code: "+230",
    value: "Mauritius",
    custom_country_value: "140",
  },
  {
    custom_country_icon: "YT",
    custom_dial_code: "+262",
    value: "Mayotte",
    custom_country_value: "141",
  },
  {
    custom_country_icon: "MX",
    custom_dial_code: "+52",
    value: "Mexico",
    custom_country_value: "142",
  },
  {
    custom_country_icon: "FM",
    custom_dial_code: "+691",
    value: "Micronesia",
    custom_country_value: "143",
  },
  {
    custom_country_icon: "MD",
    custom_dial_code: "+373",
    value: "Moldova",
    custom_country_value: "144",
  },
  {
    custom_country_icon: "MC",
    custom_dial_code: "+377",
    value: "Monaco",
    custom_country_value: "145",
  },
  {
    custom_country_icon: "MN",
    custom_dial_code: "+976",
    value: "Mongolia",
    custom_country_value: "146",
  },
  {
    custom_country_icon: "MS",
    custom_dial_code: "+1664",
    value: "Montserrat",
    custom_country_value: "147",
  },
  {
    custom_country_icon: "MA",
    custom_dial_code: "+212",
    value: "Morocco",
    custom_country_value: "148",
  },
  {
    custom_country_icon: "MZ",
    custom_dial_code: "+258",
    value: "Mozambique",
    custom_country_value: "149",
  },
  {
    custom_country_icon: "MM",
    custom_dial_code: "+95",
    value: "Myanmar",
    custom_country_value: "150",
  },
  {
    custom_country_icon: "NA",
    custom_dial_code: "+264",
    value: "Namibia",
    custom_country_value: "151",
  },
  {
    custom_country_icon: "NR",
    custom_dial_code: "+674",
    value: "Nauru",
    custom_country_value: "152",
  },
  {
    custom_country_icon: "NP",
    custom_dial_code: "+977",
    value: "Nepal",
    custom_country_value: "153",
  },
  {
    custom_country_icon: "null",
    custom_dial_code: "+599",
    value: "Netherlands Antilles",
    custom_country_value: "154",
  },
  {
    custom_country_icon: "NL",
    custom_dial_code: "+31",
    value: "Netherlands",
    custom_country_value: "155",
  },
  {
    custom_country_icon: "NC",
    custom_dial_code: "+687",
    value: "New Caledonia",
    custom_country_value: "156",
  },
  {
    custom_country_icon: "NZ",
    custom_dial_code: "+64",
    value: "New Zealand",
    custom_country_value: "157",
  },
  {
    custom_country_icon: "NI",
    custom_dial_code: "+505",
    value: "Nicaragua",
    custom_country_value: "158",
  },
  {
    custom_country_icon: "NE",
    custom_dial_code: "+227",
    value: "Niger",
    custom_country_value: "159",
  },
  {
    custom_country_icon: "NG",
    custom_dial_code: "+234",
    value: "Nigeria",
    custom_country_value: "160",
  },
  {
    custom_country_icon: "NU",
    custom_dial_code: "+683",
    value: "Niue",
    custom_country_value: "161",
  },
  {
    custom_country_icon: "NF",
    custom_dial_code: "+672",
    value: "Norfolk Island",
    custom_country_value: "162",
  },
  {
    custom_country_icon: "MP",
    custom_dial_code: "+1670",
    value: "Northern Mariana Islands",
    custom_country_value: "163",
  },
  {
    custom_country_icon: "NO",
    custom_dial_code: "+47",
    value: "Norway",
    custom_country_value: "164",
  },
  {
    custom_country_icon: "OM",
    custom_dial_code: "+968",
    value: "Oman",
    custom_country_value: "165",
  },
  {
    custom_country_icon: "PK",
    custom_dial_code: "+92",
    value: "Pakistan",
    custom_country_value: "166",
  },
  {
    custom_country_icon: "PW",
    custom_dial_code: "+680",
    value: "Palau",
    custom_country_value: "167",
  },
  {
    custom_country_icon: "PS",
    custom_dial_code: "+970",
    value: "Palestinian Territory Occupied",
    custom_country_value: "168",
  },
  {
    custom_country_icon: "PA",
    custom_dial_code: "+507",
    value: "Panama",
    custom_country_value: "169",
  },
  {
    custom_country_icon: "PG",
    custom_dial_code: "+675",
    value: "Papua new Guinea",
    custom_country_value: "170",
  },
  {
    custom_country_icon: "PY",
    custom_dial_code: "+595",
    value: "Paraguay",
    custom_country_value: "171",
  },
  {
    custom_country_icon: "PE",
    custom_dial_code: "+51",
    value: "Peru",
    custom_country_value: "172",
  },
  {
    custom_country_icon: "PH",
    custom_dial_code: "+63",
    value: "Philippines",
    custom_country_value: "173",
  },
  {
    custom_country_icon: "PN",
    custom_dial_code: "+64",
    value: "Pitcairn Island",
    custom_country_value: "174",
  },
  {
    custom_country_icon: "PL",
    custom_dial_code: "+48",
    value: "Poland",
    custom_country_value: "175",
  },
  {
    custom_country_icon: "PT",
    custom_dial_code: "+351",
    value: "Portugal",
    custom_country_value: "176",
  },
  {
    custom_country_icon: "PR",
    custom_dial_code: "+1787",
    value: "Puerto Rico",
    custom_country_value: "177",
  },
  {
    custom_country_icon: "QA",
    custom_dial_code: "+974",
    value: "Qatar",
    custom_country_value: "178",
  },
  {
    custom_country_icon: "RE",
    custom_dial_code: "+262",
    value: "Reunion",
    custom_country_value: "179",
  },
  {
    custom_country_icon: "RO",
    custom_dial_code: "+40",
    value: "Romania",
    custom_country_value: "180",
  },
  {
    custom_country_icon: "RU",
    custom_dial_code: "+7",
    value: "Russian Federation",
    custom_country_value: "181",
  },
  {
    custom_country_icon: "RW",
    custom_dial_code: "+250",
    value: "Rwanda",
    custom_country_value: "182",
  },
  {
    custom_country_icon: "SH",
    custom_dial_code: "+290",
    value: "Saint Helena",
    custom_country_value: "183",
  },
  {
    custom_country_icon: "KN",
    custom_dial_code: "+1869",
    value: "Saint Kitts And Nevis",
    custom_country_value: "184",
  },
  {
    custom_country_icon: "LC",
    custom_dial_code: "+1758",
    value: "Saint Lucia",
    custom_country_value: "185",
  },
  {
    custom_country_icon: "PM",
    custom_dial_code: "+508",
    value: "Saint Pierre and Miquelon",
    custom_country_value: "186",
  },
  {
    custom_country_icon: "VC",
    custom_dial_code: "+1784",
    value: "Saint Vincent And The Grenadines",
    custom_country_value: "187",
  },
  {
    custom_country_icon: "WS",
    custom_dial_code: "+685",
    value: "Samoa",
    custom_country_value: "188",
  },
  {
    custom_country_icon: "SM",
    custom_dial_code: "+378",
    value: "San Marino",
    custom_country_value: "189",
  },
  {
    custom_country_icon: "ST",
    custom_dial_code: "+239",
    value: "Sao Tome and Principe",
    custom_country_value: "190",
  },
  {
    custom_country_icon: "SA",
    custom_dial_code: "+966",
    value: "Saudi Arabia",
    custom_country_value: "191",
  },
  {
    custom_country_icon: "SN",
    custom_dial_code: "+221",
    value: "Senegal",
    custom_country_value: "192",
  },
  {
    custom_country_icon: "RS",
    custom_dial_code: "+381",
    value: "Serbia",
    custom_country_value: "193",
  },
  {
    custom_country_icon: "SC",
    custom_dial_code: "+248",
    value: "Seychelles",
    custom_country_value: "194",
  },
  {
    custom_country_icon: "SL",
    custom_dial_code: "+232",
    value: "Sierra Leone",
    custom_country_value: "195",
  },
  {
    custom_country_icon: "SG",
    custom_dial_code: "+65",
    value: "Singapore",
    custom_country_value: "196",
  },
  {
    custom_country_icon: "SK",
    custom_dial_code: "+421",
    value: "Slovakia",
    custom_country_value: "197",
  },
  {
    custom_country_icon: "SI",
    custom_dial_code: "+386",
    value: "Slovenia",
    custom_country_value: "198",
  },
  {
    custom_country_icon: "BH",
    custom_dial_code: "+44",
    value: "Smaller Territories of the UK",
    custom_country_value: "199",
  },
  {
    custom_country_icon: "SB",
    custom_dial_code: "+677",
    value: "Solomon Islands",
    custom_country_value: "200",
  },
  {
    custom_country_icon: "SO",
    custom_dial_code: "+252",
    value: "Somalia",
    custom_country_value: "201",
  },
  {
    custom_country_icon: "ZA",
    custom_dial_code: "+27",
    value: "South Africa",
    custom_country_value: "202",
  },
  {
    custom_country_icon: "GS",
    custom_dial_code: "+500",
    value: "South Georgia",
    custom_country_value: "203",
  },
  {
    custom_country_icon: "SS",
    custom_dial_code: "+211",
    value: "South Sudan",
    custom_country_value: "204",
  },
  {
    custom_country_icon: "ES",
    custom_dial_code: "+34",
    value: "Spain",
    custom_country_value: "205",
  },
  {
    custom_country_icon: "LK",
    custom_dial_code: "+94",
    value: "Sri Lanka",
    custom_country_value: "206",
  },
  {
    custom_country_icon: "SD",
    custom_dial_code: "+249",
    value: "Sudan",
    custom_country_value: "207",
  },
  {
    custom_country_icon: "SR",
    custom_dial_code: "+597",
    value: "Suriname",
    custom_country_value: "208",
  },
  {
    custom_country_icon: "SJ",
    custom_dial_code: "47",
    value: "Svalbard And Jan Mayen Islands",
    custom_country_value: "209",
  },
  {
    custom_country_icon: "SZ",
    custom_dial_code: "+268",
    value: "Swaziland",
    custom_country_value: "210",
  },
  {
    custom_country_icon: "SE",
    custom_dial_code: "+46",
    value: "Sweden",
    custom_country_value: "211",
  },
  {
    custom_country_icon: "CH",
    custom_dial_code: "+41",
    value: "Switzerland",
    custom_country_value: "212",
  },
  {
    custom_country_icon: "SY",
    custom_dial_code: "+963",
    value: "Syria",
    custom_country_value: "213",
  },
  {
    custom_country_icon: "TW",
    custom_dial_code: "+886",
    value: "Taiwan",
    custom_country_value: "214",
  },
  {
    custom_country_icon: "TJ",
    custom_dial_code: "+992",
    value: "Tajikistan",
    custom_country_value: "215",
  },
  {
    custom_country_icon: "TZ",
    custom_dial_code: "+255",
    value: "Tanzania",
    custom_country_value: "216",
  },
  {
    custom_country_icon: "TH",
    custom_dial_code: "+66",
    value: "Thailand",
    custom_country_value: "217",
  },
  {
    custom_country_icon: "TG",
    custom_dial_code: "+228",
    value: "Togo",
    custom_country_value: "218",
  },
  {
    custom_country_icon: "TK",
    custom_dial_code: "+690",
    value: "Tokelau",
    custom_country_value: "219",
  },
  {
    custom_country_icon: "TO",
    custom_dial_code: "+676",
    value: "Tonga",
    custom_country_value: "220",
  },
  {
    custom_country_icon: "TT",
    custom_dial_code: "+1868",
    value: "Trinidad And Tobago",
    custom_country_value: "221",
  },
  {
    custom_country_icon: "TN",
    custom_dial_code: "+216",
    value: "Tunisia",
    custom_country_value: "222",
  },
  {
    custom_country_icon: "TR",
    custom_dial_code: "+90",
    value: "Turkey",
    custom_country_value: "223",
  },
  {
    custom_country_icon: "TM",
    custom_dial_code: "+993",
    value: "Turkmenistan",
    custom_country_value: "224",
  },
  {
    custom_country_icon: "TC",
    custom_dial_code: "+1649",
    value: "Turks And Caicos Islands",
    custom_country_value: "225",
  },
  {
    custom_country_icon: "TV",
    custom_dial_code: "+688",
    value: "Tuvalu",
    custom_country_value: "226",
  },
  {
    custom_country_icon: "UG",
    custom_dial_code: "+256",
    value: "Uganda",
    custom_country_value: "227",
  },
  {
    custom_country_icon: "UA",
    custom_dial_code: "+380",
    value: "Ukraine",
    custom_country_value: "228",
  },
  {
    custom_country_icon: "AE",
    custom_dial_code: "+971",
    value: "United Arab Emirates",
    custom_country_value: "229",
  },
  {
    custom_country_icon: "GB",
    custom_dial_code: "+44",
    value: "United Kingdom",
    custom_country_value: "230",
  },
  {
    custom_country_icon: "US",
    custom_dial_code: "+1",
    value: "United States",
    custom_country_value: "231",
  },
  {
    custom_country_icon: "US",
    custom_dial_code: "+1",
    value: "United States Minor Outlying Islands",
    custom_country_value: "232",
  },
  {
    custom_country_icon: "UY",
    custom_dial_code: "+598",
    value: "Uruguay",
    custom_country_value: "233",
  },
  {
    custom_country_icon: "UZ",
    custom_dial_code: "+998",
    value: "Uzbekistan",
    custom_country_value: "234",
  },
  {
    custom_country_icon: "VU",
    custom_dial_code: "+678",
    value: "Vanuatu",
    custom_country_value: "235",
  },
  {
    custom_country_icon: "BH",
    custom_dial_code: "+379",
    value: "Vatican City State (Holy See)",
    custom_country_value: "236",
  },
  {
    custom_country_icon: "VE",
    custom_dial_code: "+58",
    value: "Venezuela",
    custom_country_value: "237",
  },
  {
    custom_country_icon: "VN",
    custom_dial_code: "+84",
    value: "Vietnam",
    custom_country_value: "238",
  },
  {
    custom_country_icon: "VG",
    custom_dial_code: "+1284",
    value: "Virgin Islands (British)",
    custom_country_value: "239",
  },
  {
    custom_country_icon: "VI",
    custom_dial_code: "+1340",
    value: "Virgin Islands (US)",
    custom_country_value: "240",
  },
  {
    custom_country_icon: "WF",
    custom_dial_code: "+681",
    value: "Wallis And Futuna Islands",
    custom_country_value: "241",
  },
  {
    custom_country_icon: "EH",
    custom_dial_code: "+212",
    value: "Western Sahara",
    custom_country_value: "242",
  },
  {
    custom_country_icon: "YE",
    custom_dial_code: "+967",
    value: "Yemen",
    custom_country_value: "243",
  },
  {
    custom_country_icon: "BH",
    custom_dial_code: "+38",
    value: "Yugoslavia",
    custom_country_value: "244",
  },
  {
    custom_country_icon: "ZM",
    custom_dial_code: "+260",
    value: "Zambia",
    custom_country_value: "245",
  },
  {
    custom_country_icon: "ZW",
    custom_dial_code: "+263",
    value: "Zimbabwe",
    custom_country_value: "246",
  },
];

export default CountriesConstant;
